# Base configuration
baseURL: 'https://matthewdickens.com/'
languageCode: 'en-us'
title: 'Matt Dickens'
theme: 'PaperMod'

# Menu
menu:
  main:
  - name: Home
    pageRef: /
    weight: 1
  - name: About
    pageRef: /about
    weight: 2
  - name: Posts
    pageRef: /posts
    weight: 3
  - name: Projects
    pageRef: /projects
    weight: 4
  - name: Resume
    url: ./resume.pdf
    weight: 5
  - name: Github
    url: https://github.com/Toltar
    weight: 6


params:
  author: "Matthew Dickens"
  description: "Thoughts on Technology"
  Headshot: "/headshot.jpg"
  Resume: "resume.pdf"